# Generated by Django 5.2.5 on 2025-09-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniai', '0004_chatmessage_user_documentchunk_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gcs_chunks_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gcs_vector_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
