runtime: python39
entrypoint: gunicorn -b :$PORT backEnd.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: "backEnd.settings"
  DB_HOST: "35.224.143.5"
  DB_PORT: "5432"
  DB_NAME: "gen-ai"
  DB_USER: "postgres"
  DB_PASSWORD: "Temp#1234"
  GCP_PROJECT: "gen-ai-legal"
  GCS_BUCKET_NAME: "legal-agreement-analyzer-gen-ai-legal"
  GOOGLE_CLIENT_ID: "635041936120-au88fng3u2ni46f368tu8b1dsbhtt17l.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto