# Generated by Django 5.2.5 on 2025-09-13 09:02

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuid_generate_v4'), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField()),
                ('agreement_type', models.CharField(max_length=100)),
                ('word_count', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('document', models.OneToOneField(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='geniai.document')),
            ],
            options={
                'db_table': 'summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuid_generate_v4'), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='geniai.document')),
            ],
            options={
                'db_table': 'processing_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'status'], name='processing__documen_6e4311_idx'), models.Index(fields=['status', 'created_at'], name='processing__status_ac8e44_idx')],
            },
        ),
    ]
