# Generated by Django 5.2.5 on 2025-09-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniai', '0002_documentsummary_processingjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsummary',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='AI confidence score for the summary', null=True),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='key_points',
            field=models.JSONField(blank=True, help_text='JSON array of key points extracted', null=True),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='risk_factors',
            field=models.JSONField(blank=True, help_text='JSON array of identified risk factors', null=True),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='agreement_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='documentsummary',
            index=models.Index(fields=['document'], name='summaries_documen_ccb17f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsummary',
            index=models.Index(fields=['agreement_type'], name='summaries_agreeme_c91ceb_idx'),
        ),
    ]
